require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/**/*

Metrics/LineLength:
  Max: 120
