version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=literature_list_generator
      - POSTGRES_DB=literature_list_generator_production
    volumes:
      - postgres_data:/var/lib/postresql/data
    ports:
      - 5432:5432
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - ROBERT_LEGAL_DATABASE_HOST=postgres
      - RAILS_ENV=production
      - RACK_ENV=production
    depends_on:
      - postgres
    volumes:
      - rails_app_public:/app/public
  nginx:
    image: nginx
    volumes:
      - rails_app_public:/usr/share/nginx/html:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

volumes:
  rails_app_public:
  postgres_data:
