version: '3'
services:
#  nginx:
#    image: nginx
#    container_name: nginx_production
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - 80:80
#      - 443:443
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=literature_list_generator
      - POSTGRES_DB=literature_list_generator_production
    volumes:
      - ./tmp/volumes/postgres:/var/lib/postresql/data
    ports:
      - 5432:5432
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - ROBERT_LEGAL_DATABASE_HOST=postgres
      - RAILS_ENV=production
      - RACK_ENV=production
    depends_on:
      - postgres
    volumes:
      - .:/app
